runmode: debug                 # 开发模式, debug, release, test
addr: :8080                    # HTTP 绑定端口
name: api-service              # API Server 的名字
url: http://127.0.0.1:8080     # pingServer 函数请求的 API 服务器的 ip:port
max_ping_count: 10             # pingServer 函数 try 的次数
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
tls:
  addr: :8081
  cert: conf/server.crt
  key: conf/server.key
log:
  writers: stdout
  logger_level: DEBUG
  logger_file: log/api-service.log
  log_format_text: true
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: db_api-service
  addr: 127.0.0.1:3306
  username: root
  password: root
docker_db:
  name: db_api-service
  addr: 127.0.0.1:3306
  username: root
  password: root
